# Generated by Django 3.2.5 on 2021-07-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20210725_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='hood_logo',
            field=models.ImageField(default='default.jpeg', upload_to='images/'),
        ),
    ]
